# Generated by Django 4.2.15 on 2024-08-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
