name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
          python-version: ["3.12"]
          node-version: [20.x]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build with Makefile
        run: make all
